// src/components/layout/Header.vue
<script setup lang="ts">
import { Icon } from '@iconify/vue';

defineEmits<{
  toggleSidebar: [];
}>();
</script>

<template>
  <header class="h-16 bg-white border-b border-gray-200 flex items-center px-4 lg:px-6">
    <button
      class="lg:hidden h-10 w-10 grid place-items-center rounded-lg hover:bg-gray-100 mr-2"
      @click="$emit('toggleSidebar')"
    >
      <Icon
        icon="mdi:menu"
        class="text-[24px]"
      />
    </button>
    <div class="flex-1 flex items-center gap-3">
      <div class="relative flex-1 max-w-xl">
        <input
          type="text"
          placeholder="Cari invoice, surat jalan, tracking..."
          class="w-full h-10 pl-10 pr-3 rounded-lg bg-gray-50 border border-gray-200 outline-none focus:ring-2 focus:ring-blue-200 text-sm"
        >
        <Icon
          icon="mdi:magnify"
          class="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500"
        />
      </div>
    </div>
    <button class="h-10 w-10 grid place-items-center rounded-lg hover:bg-gray-100">
      <Icon
        icon="mdi:bell-outline"
        class="text-[20px]"
      />
    </button>
  </header>
</template>

// design-dashboard-figma/src/components/Header.tsx
import { Menu, Notification, Search } from "@carbon/icons-react";

interface HeaderProps {
  setSidebarOpen: (open: boolean) => void;
}

export function Header({ setSidebarOpen }: HeaderProps) {
  return (
    <header className="h-16 bg-white border-b border-[#e5e7eb] px-5 md:px-7 flex items-center justify-between">
      <div className="flex items-center gap-4 flex-1">
        <button
          onClick={() => setSidebarOpen(true)}
          className="lg:hidden p-1.5 hover:bg-[#f3f4f6] rounded-md transition-colors"
        >
          <Menu size={20} className="text-[#374151]" />
        </button>

        <div className="hidden md:flex items-center gap-2.5 bg-[#f9fafb] px-3.5 py-2 rounded-md flex-1 max-w-md border border-[#e5e7eb]">
          <Search size={17} className="text-[#9ca3af]" />
          <input
            type="text"
            placeholder="Cari invoice, surat jalan, tracking..."
            className="bg-transparent outline-none flex-1 text-[13px] text-[#374151] placeholder:text-[#9ca3af]"
          />
        </div>
      </div>

      <div className="flex items-center gap-1">
        <button className="relative p-2 hover:bg-[#f3f4f6] rounded-md transition-colors">
          <Notification size={19} className="text-[#374151]" />
          <span className="absolute top-1 right-1 w-2 h-2 bg-[#ef4444] rounded-full border-2 border-white"></span>
        </button>
      </div>
    </header>
  );
}
